---
title: "ParallelComputing"
author: "Brandon"
date: "10/21/2021"
output:
  md_document:
    variant: gfm
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list=ls())

#Script modified from
#http://r-statistics.co/Parallel-Computing-With-R.html
```

# Register a SOCK and number of cores 

```{r}
# Registering cores for parallel process
library(doSNOW)

cl <- makeCluster(2, type="SOCK") # 4 – number of cores
registerDoSNOW(cl) # Register back end Cores for Parallel Computing
```

# Some simple parallel code 

```{r}
library(foreach)
foreach(i = 1:28) %dopar% {sqrt(i)} # example 1
```


```{r}
# returned output values of the parallel process are combined using 'c()' function
foreach(i = 1:28,.combine = "c") %dopar% {sqrt(i)} # example 2
```


```{r}
# returned output values of the parallel process are combined using 'cbind()' function
foreach(i = 1:28,.combine = "cbind") %dopar% {letters[1:4]} # example 3
```


```{r}
# Using your custom defined function: "myCustomFunc()" and store in 'output' variable # Example 4
myCustomFunc <- function(i){sqrt(i)+25}

output <- foreach(i = 1:28, .combine = "cbind") %dopar% {
  myCustomFunc(i)
}
```


```{r}
stopCluster(cl)
```

# Examples 

inputData <- matrix(1:800000, ncol=4) # prepare input data

output = col1 - col2 + col3 / col4

```{r}
inputData <- matrix(1:80000, ncol=4)

output_serial <- numeric() # initialize output

for (rowNum in c(1:nrow(inputData))) {
  calculatedOutput <- inputData[rowNum, 1] - inputData[rowNum, 2] + inputData[rowNum, 3] / inputData[rowNum, 4] # compute output
  output_serial <- c(output_serial, calculatedOutput) # append to output variable
}

head(output_serial)
```

# Running in Parallel 

```{r}
library(doSNOW)

cl <- makeCluster(2, type = "SOCK") # 4 – number of cores
registerDoSNOW(cl) # Register Backend Cores for Parallel Computing
allRowIndices <-
  c(1:nrow(inputData)) # row numbers of inputData, that will be processed in parallel

output_parallel <-
  foreach (rowNum = allRowIndices, .combine = c) %dopar% {
    
    # compute output
    
    calculatedOutput <-
      inputData[rowNum, 1] - inputData[rowNum, 2] + inputData[rowNum, 3] / inputData[rowNum, 4] 
    
    return (calculatedOutput)
  }

head(output_parallel)
```

# Calculate the time needed to run the two functions 

```{r}
system.time(
  for (rowNum in c(1:nrow(inputData))) {
    calculatedOutput <- inputData[rowNum, 1] - inputData[rowNum, 2] + inputData[rowNum, 3] / inputData[rowNum, 4] 
    
    # compute output
    output_serial <- c(output_serial, calculatedOutput) # append to output variable
  }
)
```

```{r}
system.time(
  output_parallel <- foreach (rowNum = allRowIndices, .combine = c) %dopar% {
    calculatedOutput <- inputData[rowNum, 1] - inputData[rowNum, 2] + inputData[rowNum, 3] / inputData[rowNum, 4] # compute output
    return (calculatedOutput)
  }
)
```

#  When parallelism actually matters 

```{r}
inputData <- matrix(1:1000000, ncol=4)

series_time <- system.time(
  for (rowNum in c(1:nrow(inputData))) {
    calculatedOutput <- inputData[rowNum, 1] - inputData[rowNum, 2] + inputData[rowNum, 3] / inputData[rowNum, 4] 
    
    # compute output
    output_serial <- c(output_serial, calculatedOutput) # append to output variable
  }
)

series_time
```


```{r}
stopCluster(cl)
cl <- makeCluster(3, type = "SOCK") # 2 – number of cores
registerDoSNOW(cl) # Register Backend Cores for Parallel Computing

allRowIndices <-
  c(1:nrow(inputData)) # row numbers of inputData, that will be processed in parallel

parallel_time <- system.time(
  output_parallel <- foreach (rowNum = allRowIndices, .combine = c) %dopar% {
    calculatedOutput <- inputData[rowNum, 1] - inputData[rowNum, 2] + inputData[rowNum, 3] / inputData[rowNum, 4] # compute output
    return (calculatedOutput)
  }
)

parallel_time
```

#  Something People want to see
```{r}
plotdata <- as.data.frame(matrix(rep(1:4),ncol=2))
plotdata$type <-  c("Series","Parallel")
plotdata$elapsed <- c(series_time[3],parallel_time[3])

library(ggplot2)

ggplot(data=plotdata,aes(x=type,y=elapsed)) + geom_col()
```






